on:
  push:
    branches: [ main ]
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.3'
          channel: stable
      - name: Build apk
        run: |
          ls
          cd front
          flutter upgrade
          flutter pub get
          flutter format --set-exit-if-changed
          flutter analyze
          flutter test
          flutter build apk --debug
  build-web:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: subosito/flutter-action@v1
       with:
         flutter-version: '3.7.3'
     - name: Build apk
     - name: Build apk
       run: |
         ls
         cd front
         flutter upgrade
         flutter pub get
         flutter format --set-exit-if-changed
         flutter analyze
         flutter test
         flutter build web
