on:
  workflow_run:
    workflows:
      - Test1
    types:
      - completed
jobs: 
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/checkout@v1
      - name: show text in console
        run: |
          echo "Le workflow précédent a fail"
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v1
      - name: show text in console
        run: |
          echo "Le workflow précédent a réussi"