on:
  push:
    branches: [ main ] 
jobs: 
  build-apk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17.x'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.3'
          channel: stable
      - name: Install lcov
        run: |
          sudo apt update
          sudo apt install lcov 
      - name: Build apk
        run: |
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test --coverage
          #Remove generated sources and entities from coverage
          lcov --remove coverage/lcov.info -o coverage/lcov.info '**/*.g.dart' '**/*.freezed.dart' '**/entities/**' '**/*_state.dart' '**/core/**'
          #Generate coverage report and expose it in GitHub Pages repository
          genhtml coverage/lcov.info -o docs/ 
          flutter build apk --debug
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
           flutter-version: '3.7.3'
      - name: Build web
        run: |
          ls
          cd front
          flutter upgrade
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build web
  build-back:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: back
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Build
        run: |
          npm ci
          npm run build --if-present
          npm run test
      - name: Check content
        run: cat ./coverage/lcov.info
    
