on:
  push:
    branches: [ main ]
jobs: 
  build-apk:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17.x'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.3'
          channel: stable
      - name: Build apk
        run: |
          ls
          cd front
          flutter upgrade
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build apk --debug
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
           flutter-version: '3.7.3'
      - name: Build web
        run: |
          ls
          cd front
          flutter upgrade
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build web
  build-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Build
        run: |
          cd back
          npm ci
          npm run build --if-present
          npm run test
          ls
          cat ./coverage/lcov.info && rm -rf ./coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v1
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
    
