name: Test1

on:
  push:
    branches: [ main ] 
jobs: 
  build-apk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17.x'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.3'
          channel: stable
      - name: Install lcov
        run: |
          sudo apt update
          sudo apt install lcov 
      - name: Build apk
        run: |
          flutter upgrade
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build apk --debug
  build-web:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
           flutter-version: '3.7.3'
      - name: Build web
        run: |
          flutter upgrade
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build web
  build-back:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: back
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Build
        run: |
          npm ci
          npm run test
          npm run build --if-present
      - name: Check content
        run: cat ./coverage/lcov.info
      # ... Generate LCOV files or download it from a different job
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: ./back/coverage/lcov.info
          minimum-coverage: 0
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
    
